### ISSUE TITLE
Feature request: Weight for AMMO

### ISSUE THREAD

**Issue by dc-avasilev** [yandex/pandora#166]
Good afternoon, I would like to propose to introduce into the gun the priority of firing based on the weight of the AMMO, the greater the weight, the more priority the AMMO.
What problem would this solve?
Suppose there is a file with RAW AMMOs, I would like all AMMOs with a weight of 100 to be executed first, then with a weight of 99, then with 98, etc.
something like a script without having to write a custom gun with logic etc. since it’s corny just need a sequence in the execution of pre-prepared AMMOs

**Comment by dc-avasilev** [comment]
`{"tag": ..., "weight": int, "uri": ...}` - something like that if in json form

**Comment by oke11o** [comment]
Hi!
The way you described it sounds like ammo sorting. And you're proposing to sort the cartridges by the new weight field.
The architecture of current providers suggests that patron files can be very large, so with the default behavior providers don't read the whole file at once. Instead, they read only one cartridge at a time. Therefore there is no way to sort the cartridges.

PS: Yes, in current providers there is a setting to load the weight of the cartridge file into memory.  In this case it is possible to sort the cartridges.

**Comment by oke11o** [comment]
I can recommend you to write a custom provider using current json provider as a base. And add sorting

**Comment by dc-avasilev** [comment]
sadly, yes, I understand, "you can do it somehow yourself", I just thought about a convenient feature out of the box
