### ISSUE TITLE
Crashes on start with big "times" parameter when compiled with go 1.9.1

### ISSUE THREAD

**Issue by NinaCarrot** [yandex/pandora#74]
I got some weird random crashes of pandora compiled with go 1.9.1 with config such as ` "rps": {"type": "const", "ops": 15000, "duration": "5m"}, "startup": {"type": "once", "times": 500}`

Sometimes it's `fatal error: sweep increased allocation count`, and sometimes it's a SIGSEGV.
[pandora_ZaeI79.log](https://github.com/yandex/pandora/files/1387660/pandora_ZaeI79.log)

It seems that everything works fine when I compile with go 1.8

**Comment by skipor** [comment]
Seems to be go 1.9 problem: https://github.com/golang/go/issues/21717
We are using `reflect.Call` actively in `plugin` pkg.

**Comment by skipor** [comment]
Can't reproduce on go 1.9.2
