### ISSUE TITLE
Add http2 gun

### ISSUE THREAD

**Issue by m0sth8** [yandex/pandora#8]
https://godoc.org/golang.org/x/net/http2 - it is still under development, but works fine

**Comment by burthen** [comment]
+1 for feature request - HTTP/2 support

**Comment by direvius** [comment]
Current HTTP gun (from develop branch) can shoot over HTTP/2, but without any knobs that will allow you to simulate browser's behaviour. We plan to leave this "simple" HTTP/2 gun and add other "complex" HTTP/2 gun.
